### ISSUE TITLE
Support F# 4.7 new syntax features

### ISSUE THREAD

**Issue by nightroman** [fsharp/FSharp.Compiler.Service#912] opened 2019-09-29 06:32 UTC
Here is the list of [new features](https://devblogs.microsoft.com/dotnet/announcing-f-4-7/).

The new features of FSharp.Core library work fine, at least I tried `Async.Sequential`.

But it looks like the new syntax features are not yet supported by FCS 31.0.

### Implicit yield

The snippets below do not compile:

```fsharp
module ImplicitYieldList =
    let includeWeekend = true
    [
        "Monday"
        "Tuesday"
        "Wednesday"
        "Thursday"
        "Friday"
        if includeWeekend then
            "Saturday"
            "Sunday"
    ]
    |> printfn "%A"

module ImplicitYieldSeq =
    let includeWeekend = true
    seq {
        "Monday"
        "Tuesday"
        "Wednesday"
        "Thursday"
        "Friday"
        if includeWeekend then
            "Saturday"
            "Sunday"
    }
    |> printfn "%A"
```

### No more required double underscore 

The snippet below does not compile

```fsharp
module M1 =
    type C () =
        member _.M () = ()
```

NB Interestingly, C-style `for` loops with `_` compile (maybe it's not a new feature?)

```fsharp
for _ in 1..10 do ()
```

**Comment by nightroman** [comment] 2019-09-29 06:43
### Indentation relaxations

The snippets below give "Possible incorrect indentation" warnings

```fsharp
module Indent =
    type OffsideCheck'(a:int,
            b:int, c:int,
            d:int) = class end

    type C'() =
        static member M(a:int,
          b:int, c:int,
          d:int) = 1
```

**Comment by baronfel** [comment] 2019-09-29 15:10
Yep, I need to merge latest. I'll be doing that this week. Those changes just got merged a few days ago, so it's normal for there to be some lag time. Plus I'm sick, so bear with me.

**Comment by nightroman** [comment] 2019-09-29 16:37
@baronfel 
Thank you. Please take your time and get well soon. I have reported this just to be sure it's not forgotten and to get some estimates perhaps. The features are not that critical after all.

**Comment by baronfel** [comment] 2019-10-01 02:09
Release 32.0.0 has been merged and published to nuget. Over the next days I'll be working with other project maintainers to get the release flowed out to FSAC, Ionide, FSharpLint, and other integrated projects.

**Closed by baronfel** 2019-10-01 02:09 UTC

**Comment by nightroman** [comment] 2019-10-01 04:48
@baronfel Thank you, all is fine now.

> (preview) open static classes

Out of curiosity, how do I enable preview features? `<LangVersion>preview</LangVersion>` in my fsproj hosting scripts does not help.

**Comment by nojaf** [comment] 2019-10-01 07:08
It would be nice if a new version of the FCS also meant an update of the documentation.
I'm missing `SequentialOrImplicitYield` for example on https://fsharp.github.io/FSharp.Compiler.Service/reference/fsharp-compiler-ast-synexpr.html.
Could that be incorporated somehow?

**Comment by baronfel** [comment] 2019-10-01 11:44
Documentation generation is broken right now and it's something I'll be looking at shortly. Not quite sure the root cause, naturally, but it's something I want to get fixed. Probably after I fix scripting in ionide though :)

**Comment by baronfel** [comment] 2019-10-01 14:39
@nightroman do you have a link to these scripts that I could check out?  theoretically you should be able to set project options directly with the preview flag if necessary.

**Comment by nightroman** [comment] 2019-10-01 16:55
From F# 4.7 announcement,

```fsharp
module Test
open System.Math

let verifyMathWorks () =
    printfn "Just verifying that sin(pi) is indeed zero..."
    Sin(PI) = 0.0

[<AbstractClass; Sealed>]
type MyStaticClass =
    static member L(x: int) = x
    static member M(x: int) = x
    static member N(x: int) = x
    static member O(x: int) = x
    static member P(x: int) = x

open MyStaticClass

let x = 12
let xAgain = L(M(N(O(P(x)))))
```

It's not happy about `open System.Math` and `open MyStaticClass`.

> theoretically you should be able to set project options directly with the preview flag if necessary.

I would try but does it mean, what project exactly?

**Comment by baronfel** [comment] 2019-10-01 17:01
Conceptually, to typecheck any F# code you need a `ProjectOptions` which describes references. In most editors, this is derived from evaluating your `fsproj` file. In script files this comes from some default settings + any editor-specific customizations you would like to apply. If you are running scripts via fsi directly, then you should be able to add the flag like so:

````
dotnet /path/to/fsi.exe --langversion:preview /path/to/script/file.fsx
```

When you said you had 'fsproj hosting scripts', what does this mean?

**Comment by nightroman** [comment] 2019-10-01 17:52
> --langversion:preview

Yes, that what I was looking for, thank you, problem solved.

> When you said you had 'fsproj hosting scripts', what does this mean?

My application (add-on library for another app, in fact) project that uses FCS to run the main app scriting. Does not really matter, the problem is solved.
