### ISSUE TITLE
Report bound top-level variables from EvalInteraction

### ISSUE THREAD

**Issue by tpetricek** [fsharp/FSharp.Compiler.Service#563] opened 2016-05-10 11:22 UTC
I'm trying to reimplement some of the FSI functionality for Ionide based on the F# compiler service (see the [FsInteractiveService project](https://github.com/ionide/FsInteractiveService)). 

One thing that does not seem to be possible at the moment is to get top-level bindings that were produced by an `EvalInteraction` command. For example, say I use Deedle and call:

```
fsi.EvalInteraction("let myseries = series [ 1 => 3.14 ]") 
```

I would like to be able to find know that this defined `myseries` value, so that I can display the series nicely in a grid. At the moment, I'm only able to do this if the evaluated text is an expression (I get the `it` value and see if that's a series), but not for bound variables.

**Comment by dsyme** [comment] 2017-05-02 08:59
Closing as duplicate of #280

**Closed by dsyme** 2017-05-02 08:59 UTC
Labels: feature request
