### ISSUE TITLE
I want to get fields defined in C# from FSharpEntity.

### ISSUE THREAD

**Issue by hafuu** [fsharp/FSharp.Compiler.Service#532] opened 2016-02-13 10:18 UTC
There is no way to get fields defined in C# (ex. System.Int32.MaxValue).
On the other hand, It is able to get F# fields (like struct defined in F#, record) by `FSharpEntity.FSharpFields`.

There is also a way to use reflection, but it can not get the F# type name of field signature.
For example, option is compiled as FSharpOption by CompiledNameAttribute.

**Comment by dsyme** [comment] 2017-05-02 09:01
Closing as duplicate of https://github.com/fsharp/FSharp.Compiler.Service/issues/235

**Closed by dsyme** 2017-05-02 09:01 UTC
Labels: feature request
