### ISSUE TITLE
Take IFileSystem as an (optional) argument

### ISSUE THREAD

**Issue by fsoikin** [fsharp/FSharp.Compiler.Service#289] opened 2015-01-08 23:25 UTC
How come `IFileSystem` is static mutable?
Seems like a no-brainer to pass it in as an argument, so the whole compiler service can be used in isolation.

**Comment by 7sharp9** [comment] 2015-01-08 23:54
So the type check / compiler environment can be changed without having to pass that argument each time.

**Comment by fsoikin** [comment] 2015-01-09 00:23
I don't understand what's wrong with passing that argument every time.

**Comment by dsyme** [comment] 2015-01-14 19:41
I think Dave means "without having to *set* that argument every time"

**Comment by fsoikin** [comment] 2015-01-14 20:19
Still.
Consider these two fragments:

```
Shim.FileSystem <- myFileSystem
let checker = FSharpChecker.Create( ... )
let res = checker.ParseCheckWhatever( ... )
```

vs.

```
let checker = FSharpChecker.Create( shimFileSystem=myFileSystem, ... )
let res = checker.ParseCheckWhatever( ... )
```

The second fragment doesn't involve any extra effort (in fact, it involves a few characters _less_ typing, and even less if you're willing to lose named arguments), but at the same time the checker (or whatever other service) to be used concurrently by multiple consumers within the same app domain (think web app running F# scripts submitted by users).

I just don't understand why would the FS shim ever be a static mutable variable. It's just such an antipattern...

**Comment by 7sharp9** [comment] 2015-01-14 21:11
The checker is not usable concurrently apart from symbol resolution methods.  Everything else hours into a time sliced queue.  The issue raised could be one of api evolution, any change would have to be tested and old usages obsoleted.  I'm not sure if the virtual file system is used over all of the checker Api either.  

An optional argument would be better for usability, I wouldn't want to pass it on every use.

**Comment by fsoikin** [comment] 2015-01-15 02:51
Even if everything goes through a queue, the entry point can still be called concurrently. In other words, even if the checker is not concurrent, its consumers may be.  

And yes, of course I meant an optional argument.

**Comment by 7sharp9** [comment] 2015-01-15 09:59
The other problem is there is also a singleton `Checker` currently available -> `FSharpChecker.Instance`

**Comment by dsyme** [comment] 2015-01-15 14:11
Making it an (optional) argument would definitely be good - the reason a global is used initially is that the code changes to plumb it around were too intrusive.

**Comment by fsoikin** [comment] 2015-01-16 02:33
@7sharp9, wow, didn't realize that.
*The "right" solution* (what I would do if I was designing it from scratch): make the singleton instance use default file system (i.e. no shim). This is consistent: after all, all other checker parameters are fixed in the singleton instance. This will break some consumers who use both singleton *and* custom file system, but the break will happen at compile time, because `Shim.FileSystem` will no longer be there, and the break will be easy to fix.
*The ugly solution*: keep `Shim.FileSystem` around and use it when no file system is passed as argument. This would be completely backwards-compatible, but very ugly to implement, and also introduce more technical debt (i.e. double number of test cases).


@dsyme, that's what I imagined.

**Comment by fsoikin** [comment] 2015-07-31 15:26
@dsyme it seems that the commit message references this issue by mistake.

**Comment by dungpa** [comment] 2015-07-31 15:31
Reopening due to wrong auto-closing.

**Comment by dsyme** [comment] 2017-05-11 18:33
Spring cleaning old feature requests and suggestions in preparation for repo unification

**Comment by fsoikin** [comment] 2017-05-11 18:54
Does this mean you're dropping this suggestion?

**Comment by dsyme** [comment] 2017-05-11 21:31
@fsoikin No - it's a good suggestion.

TBH I'm not sure how to track FCS issues.   We've decided to "unify" _development_ of FCS so that contributions go first to Microsoft/visualfsahrp, and we may also build and release from there.  But I'm aware that we also need a way to track the integrity (docs, bugs designs, discussions, suggestions) of FCS itself.    I'm concerned that if we move all the issues to the unified repo then the design integrity will suffer

I'll reopen this issue for now. and think about it more.  It might be we keep this repo as a place to help ensure design-integrity.

**Comment by matthid** [comment] 2017-05-11 22:29
@dsyme in a perfect world we would use one repro for all compiler relevant stuff, including the compiler api (which is fcs) and flag/tag issues. Having a sane api and abstractions usable via API  improves the code base anyway. Hell they wrote the c# compiler from scratch to get this.

yeah there are several issues, like having the vs support coupled in the repository. And I understand that changes are risky but (in my naive world view) regressions need to be caught by tests and not by stop doing changes (which sometimes seem to be the argument in the primary repository)...

Sorry for going off topic. But I think cleaning up some of these old hacks is kind of important in the long run.

**Comment by dsyme** [comment] 2017-05-12 15:59
@matthid I think technically we will operate in a unified repo - most contributions will flow via Microsoft/visualfsharp.  I'm pretty sure we will eventually update that repo to use FSharp.Compiler.Service.dll as the core component.

The main things I'm concerned about now are the other things we need to ensure design integrity and independence of FCS - so it doesn't get swamped by other concerns such as compiler correctness, tools, ...
* bug tracking
* suggestion tracking
* encouraging API design coherence
* encouraging API-level unit testing 
* docs
* packaging 

At least for a while these will remain in this repo - the Microsoft/visualfsharp repo just isn't set up well to automate the publication of docs, for example.

**Closed** 2021-08-13 13:51 UTC
Labels: feature request
