### ISSUE TITLE
Allow compilation to in memory stream

### ISSUE THREAD

**Issue by Alxandr** [fsharp/FSharp.Compiler.Service#266] opened 2014-11-14 19:17 UTC
Compiling to dynamic assembly is not viable, because there are certain things you can't do with a dynamic assembly. Having a `CompileToStream(options, stream)` would be very useful.

**Comment by adamkennedy** [comment] 2015-01-25 02:15
@Alxandr What kind of things can you do with compile to stream that you can't do with dynamic assemblies? Just curious because I have a project that is doing some rather tricky/risky things with dynamic assemblies and I'm curious what other options I have.

**Comment by Alxandr** [comment] 2015-07-31 15:24
@dsyme did you close the wrong issue from the commit?

@adamkennedy Sorry for really late reply. I must not have seen your question when it was asked first. There were a few reasons I wanted to compile to stream, and most of them has to do with the fact that it's what DNX expects, and it's (as far as I've been told, never really benchmarked this) much more performant than having to do IO. What I do today is I compile to a file (just like normal), then read that into a `MemoryStream` and delete the file, which is obviously not the best practice. Also there were some problems with compiling to dynamic assemblies back at the time, though I believe @dsyme  fixed all of those.

**Comment by dungpa** [comment] 2015-07-31 15:31
Reopening due to wrong auto-closing.

**Comment by enricosada** [comment] 2015-11-09 18:10
i added the base for in-memory compilation in a refactoring pr Microsoft/visualfsharp#715

Can you help me? i need an help about the api for stream vs files

@dsyme comment [here](https://github.com/Microsoft/visualfsharp/pull/715#discussion_r44211564)

## v1

```fsharp
type EmitStreamProvider = Lazy<Choice<EmitTo, Diagnostic>>
and EmitTo =
    | EmittedFile of string
    | EmittedStream of Stream
and Diagnostic = string
```

1. `Choice<EmitTo, Diagnostic>`:
  -  to use success/fail pattern instead of exception based control flow
  - we can refactor (later) the control flow as computation expression  
2. `Lazy`:
  -  deferred creation
  - once
  - we can ask ( `Lazy.IsValueCreated` ) if the factory is called, and easy cleanup the files on error
3. both `EmittedFile of string` and `EmittedStream of Stream` , not only `Stream`
  - performance, useless continue to copy stream (build+sign, pdb) if i need a real file
  - current implementation (pdb/sign) require file on disk, useless hide that complexity. if we later improve pdb/sign, this api is ok 
  - easy to consume api


## v2  no Diagnostc on File path ( @dsyme suggestion )

seem better because i dont expected the string filename to return an error.
An api where the type system enforce that an error is not possible is better. :+1:  I'll use your version

```fsharp
type EmitStreamProvider = Lazy<EmitTo>
and EmitTo =
    | EmittedFile of string
    | EmittedStream of Choice<Stream, Diagnostic>
and Diagnostic = string
```

now the issue is abount `Lazy` vs `unit -> `, like 

## v3

```fsharp
type EmitTo =
    | EmittedFile of string
    | EmittedStream of unit -> Choice<Stream, Diagnostic>
and Diagnostic = string
```

I'd like to encode contract of  the behaviour in the type system.

for me `(unit -> Stream)` is a problem in the contract api for the Stream:
- can be consumed multiple times, more difficult to call the api (need to dispose multiple streams)
- each call can return a different Stream
- i dont know if it'is already called ( i can track, but it'is easier to already know with `Lazy.IsValueCreated` ).

`Lazy` here is about "do that deferred, but exactly once", i can encode this requirement with a type and a DU, but lazy as type already exists.


## v3.b no factory, directly Stream

type EmitTo =
    | EmittedFile of string
    | EmittedStream of Stream
and Diagnostic = string

that mean no deferred open of stream -> the stream should be open before the compile api call


/cc @dungpa @7sharp9 @rneatherway too :smile:

**Comment by Alxandr** [comment] 2015-11-13 13:56
So, half of that last post went completely over my head, but I'll ask a few questions regardless:

1. Why do you need to differentiate between `EmittedFile` and `EmittedStream`? Particularly, why do you need to flow a file-name through the compilation process? If I'm reading this right (and I might not be) this seems to me like a bad API design. Rather, why not abstract over the fact that a compilation produces (as far as I know) up to 3 artifacts. One dll/exe, one (P)PDB, and a XML file (2 of which at least are optional), and it produces diagnostics messages (regardless of whether or not the compilation was successful. If I were to have a pick of `comile` APIs, it would look something like this:

```fsharp
type CompilationArtifacts = {
  assembly: Stream
  pdb: Stream option
  docs: Stream option
}

type CompilationResult =
| Successful of CompilationArtifacts * Diagnostic
| Failure of Diagnostic

type Compilation = {
  files: string list
  // more compiler options
}

val compile: Compile -> CompilationResult
```

**Comment by Alxandr** [comment] 2015-11-13 14:01
Also, for those who read this on email, not on github, I updated my previous comment a few times which is probably not reflected in the emails. So please read it on GitHub :)

**Comment by dsyme** [comment] 2015-11-14 10:24
@enricosada The discussions on Microsoft/visualfsharp were all about internal APIs in the src/fsharp codebase.  I think it would be better to discuss the FCS API in the context of a PR to FCS since the idioms and the design are different.

@alexischr In the Microsoft/visualfsharp PR, the filename was propagated through ilwrite.fs largely to keep the diff absolutely minimalist in the non-stream cases. Without that, the PR could not be accepted into Microsoft/visualfsharp - it is not implementing functionality there, but only being integrated to keep the FCS and F# Compiler codebases maximally aligned (FCS is a fork of Microsoft\visualfsharp via fsharp\fsharp).

For the public FCS API I'd imagine the API will appear as an adjustment to [the Compile methods in the SimpleSourceCodeServices API](https://github.com/fsharp/FSharp.Compiler.Service/blob/9bf7ae29435907ed30aedef936c7b7c685cd55e4/src/fsharp/vs/SimpleServices.fsi#L108). However we should really merge SimpleSourceCodeServices with SourceCodeServices in any case - most of the functionality in SSCS has been deprecated (it wasn't really much "simpler"), and they are better merged.  Also, the compilations in SimpleSourceCodeServices should be be run through the Reactor queue of SourceCodeServices.

@alexischr Is referencing a Stream output necessary?  I hadn't realised that.  That would be ok - we can also adjust FCS to do be able to do this (probably by reading all bytes from the stream in any case in the first instance).  The streams would be specified by a type in the FCS Compile API something like you have.

@alexischr I know you don't like the fact that FCS takes its arguments specified as textual command line flags.  For now that's likely to continue and we should make that orthogonal to this PR.

**Comment by Alxandr** [comment] 2015-11-14 10:56
@dsyme So, I'm assuming you just misspelled my name and most of your last messages was directed at me :P.

Yes, allowing references to be streams is required. The goal is to allow for compilation without *any* IO. Another thing that would also be great wrt DNX is the ability to emit reference only assemblies (assemblies with only the type table as far as I've understood it, and no IL). But I agree, not everything needs to be handled as one issue.

My goal was just to try to take a more higher level look at things, as I personally don't know too much of the F# internals. Also, IMHO, the string based argument parsing solution has several issues that needs to be resolved, and that I can see no other way of resolving than allowing for a better typed API, among which are the fact that references needs to be strings. In fsharp-dnx, to work with DNX, I have to take the stream I receive from DNX as a reference, write it to a temporary file, compile against that temporary file to another temporary file, read the second temporary file into memory, then finally clean up after myself. This is not elegant, it's not efficient, and the code becomes harder to reason about.

Oh, and one thing I forgot, another thing the DNX compiler expects a "language compiler service" to be able to do is to generate just diagnostics (without doing any compilation). So just stopping before the emit stage is reached should also be an option, but I guess that really should be it's own issue.

**Comment by dsyme** [comment] 2015-11-14 11:18
@Alxandr - fixed the comment thanks.   

Re diagnostics - the SourceCodeServices API already has the ability to just produce diagnostics (ParseAndCheckProject).  One reason for moving the two Source-code-services APIs together is to align them and make this clearer.

**Comment by dsyme** [comment] 2017-05-11 18:39
Spring cleaning old suggestion issues in preparation for repo unification

**Closed by dsyme** 2017-05-11 18:39 UTC
Labels: feature request

**Comment by Mobrockers** [comment] 2020-11-09 13:56
@dsyme we very much would like an in memory stream API in stryker-mutator/stryker-net because as a mutation testing framework we often introduce code that does not compile which means we have to recompile often.

In csharp we use the following loop:

1. Add mutations in AST

1. present stream + AST to roslyn 
2.1.  read diagnostic messages and remove mutations on compile error locations 
2.2. present stream + AST to roslyn again 

1. Repeat 2 until there are no compilation errors
1. Write stream to file

This gives us 2 things

- We don't waste cycles on useless IO
- Roslyn is able to use the existing compilation to do incremental compilations (very fast)

Incremental compilations would be nice to have but limiting disk IO would be very very helpful for us to limit the cycles we spend on compiling instead of running mutation tests.
