### ISSUE TITLE
FCS + PowerTools breaking F# Formatting

### ISSUE THREAD

**Issue by tpetricek** [fsharp/FSharp.Compiler.Service#510] opened 2016-01-12 19:30 UTC
I seem to be repeatedly getting into issues when I update F# Formatting to use a new version of Visual F# PowerTools and F# Compiler service. 

Most recently, I started getting the following error when referencing F# Formatting from the FsSnip project (https://github.com/tpetricek/FsSnip.Website):

    System.TypeInitializationException: The type initializer for '<StartupCode$FSI_0001>.$FSI_0001_App$fsx' threw an exception. ---> 
    System.TypeInitializationException: The type initializer for 'FSI_0001.FsSnip.Snippet' threw an exception. ---> 
    System.TypeInitializationException: The type initializer for '<StartupCode$FSI_0001>.$FSI_0001_FsSnip.Snippet' threw an exception. ---> 
    System.TypeInitializationException: The type initializer for 'FSI_0001.FsSnip.Utils' threw an exception. ---> 
    System.TypeInitializationException: The type initializer for '<StartupCode$FSI_0001>.$FSI_0001_FsSnip.Utils' threw an exception. ---> 
    System.MissingMethodException: Method not found: 'Void Microsoft.FSharp.Compiler.SourceCodeServices.FSharpChecker.set_ImplicitlyStartBackgroundWork(Boolean)'.
   at FSharpVSPowerTools.LanguageService..ctor(FSharpOption`1 backgroundCompilation, FSharpOption`1 projectCacheSize, FSharpOption`1 fileSystem)

It was only happening inside Azure (I was suspecting wrong F# Core reference?) but it started working when I downgraded F# Compiler service to 1.4.2 (see [this change](https://github.com/tpetricek/FsSnip.Website/commit/db9fc7fbf9712a0d3515f75a44a7f605e17c2ee2#diff-b27553841b4413a24ed1b9aff865105bL7)). I do not really see why, because the method exists in the newest version too and it does not reference any F# Core types.

I think there might be more general issue here though because `FSharpVSPowerTools.Core` package references `FSharp.Compiler.Service (≥ 1.4.2)`, but I think what it really means is that it needs _exactly_ `1.4.2` because newer versions of F# Compiler Service often break compatibility.

@matthid @dsyme @vasily-kirichenko @dungpa What should we do here?

Should F# Compiler Service not have breaking changes within sub-versions? Or should PowerTools have a fixed-version dependency? Or am I missing something?

**Comment by matthid** [comment] 2016-01-12 21:48
The problem is that both projects don't really have developed a versioning story jet, so it's hard to depend on them properly (at least I didn't saw any definition anywhere when which number gets increased for either project, I think @dsyme suggested somewhere to switch to semver which would be very welcome). I don't think including breaking changes in the last version number is a good idea no matter the versioning story.

This is definitly related to https://github.com/tpetricek/FSharp.Formatting/issues/337 in the sense that even when we (FSF) pin the versions it wouldn't help currently in all situations :). All projects referencing FCS feel quite versatile at the moment (even more when FAKE is involved).

**Comment by dsyme** [comment] 2016-01-12 23:31
FCS can now use SemVer.

The 1.4.2 series is meant to be binary compatible - it would be good to determine why it isn't and what we can do to test compat.

**Comment by matthid** [comment] 2016-01-13 19:00
Without actually reproducing anything this is probaly in fact another instance of tpetricek/FSharp.Formatting#337 and there is no bug here at FCS.

@tpetricek while you downgraded FCS you also upgraded FAKE from [4.4.1 bundling FCS 1.4.0.1](https://github.com/fsharp/FAKE/blob/4.4.1/paket.lock#L20) to [4.14.0 bundling FCS 1.4.2.1](https://github.com/fsharp/FAKE/blob/4.14.0/paket.lock#L19). Note that 1.4.0.1 doesn't contain the method while 1.4.2.1 does. You can simply verify this by unlocking FCS in the paket.dependences file and after updating FCS it should still work.

@forki Thank you for giving us lockfiles :+1: 

Related https://github.com/fsprojects/Paket/issues/1381 its definitly a problem across all the three projects (FAKE, Paket, FSF)

**Comment by tpetricek** [comment] 2016-01-14 01:13
Aaah, I think it is FAKE update as @matthid says.

I wonder if FAKE could use some AppDomain magic when running the scripts to make sure it is not preventing us from loading another version of FCS?

**Comment by matthid** [comment] 2016-01-14 18:59
I think this needs to be a FCS feature. But I don't know if it is worth to implement as everything is moving towards CoreCLR and it doesn't support AppDomains :(

**Comment by dsyme** [comment] 2016-03-30 03:49
Closing this as I don't see a specific fix we can make in FCS

**Closed by dsyme** 2016-03-30 03:49 UTC
