### ISSUE TITLE
AST differences on Linux vs Windows

### ISSUE THREAD

**Issue by TheAngryByrd** [fsharp/FSharp.Compiler.Service#920] opened 2020-01-17 21:21 UTC
Hey there! I'm working on creating plugins for [FSharp.Analyzers](https://github.com/ionide/FSharp.Analyzers.SDK).  `FSharp.Analyzers` typically uses the [Typed AST](https://github.com/ionide/FSharp.EventHorizon/blob/master/src/FSharp.EventHorizon.Analyzer/Library.fs#L125) to do its analysis.  I'm working on some analyzers [over here](https://github.com/BinaryDefense/BinaryDefense.FSharp.Analyzers) but I'm running into issues on my [Windows builds](https://github.com/BinaryDefense/BinaryDefense.FSharp.Analyzers/runs/391497057).  The AST on windows isn't the same as the ones on linux/macos. 

I've created [a gist](https://gist.github.com/TheAngryByrd/6cd82cdc2cde2e696f49dce4c1e1bc27) showing off the library code and subsequent typed ASTs for each platform.  What's interesting is the `Windows` TAST is placing `(None,val raise,[],[type Microsoft.FSharp.Core.obj],` in places where you'd expect the correct calls to `ComputeHash` like `(Some Value val md5provider,member ComputeHash,[],[],`.  It seems like it's erroring while creating the tree and capturing that as part of the TAST instead of outright failing.

To load the TAST I'm using the following code from [This file](https://github.com/BinaryDefense/BinaryDefense.FSharp.Analyzers/blob/master/tests/BinaryDefense.FSharp.Analyzers.Tests/Analyzer.fs) 

```fsharp
let checker =
    FSharpChecker.Create(
        projectCacheSize = 200,
        keepAllBackgroundResolutions = true,
        keepAssemblyContents = true,
        ImplicitlyStartBackgroundWork = true)

checker.GetProjectOptionsFromScript(file, SourceText.ofString source, assumeDotNetFramework = false, useSdkRefs = true, useFsiAuxLib = true, otherFlags = [|"--targetprofile:netstandard" |])
```

**Repro steps**

1. Pull [the analyzers](https://github.com/BinaryDefense/BinaryDefense.FSharp.Analyzers/blob/master/tests/BinaryDefense.FSharp.Analyzers.Tests/Analyzer.fs) project.
2. run `build.cmd` on windows
3. Tests should fail

**Expected behavior**

TAST on Windows is the same as Linux/macOS

**Actual behavior**

TAST on Windows is generating `raises` instead of actually calls.

**Known workarounds**

??

**Related information**

Provide any related information (optional):

* Operating system : Windows
* .NET Runtime kind (.NET Core, .NET Framework, Mono): Netcore
* Editing Tools (e.g. Visual Studio Version, Visual Studio): 

```
 dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by baronfel** [comment] 2020-01-17 22:39
@cartermp @dsyme do either of you know if there are some common root causes of the `raise` calls being generated in the AST? I'm working on getting project info for this use case to help us see what FSC thinks of the script

**Comment by dsyme** [comment] 2020-01-20 12:57
Given that the expression being generated is `raise 1` then I think it's coming from this error recovery in the type checker
```fsharp
        // Error recovery - return some rubbish expression, but replace/annotate 
        // the type of the current expression with a type variable that indicates an error 
        errorRecovery e m 
        solveTypAsError cenv env.DisplayEnv m ty
        mkThrow m ty (mkOne cenv.g m), tpenv
```
I'd imagine this is some kind of missing DLL reference on Linux.  

I think you should use debugging or printf's to try to determine 
1. why the error recovery code is being invoked (e.g. first exception being raised)
2. why the invocation of the error recovery code isn't leading to a type checking error being reported (or perhaps you are somehow ignoring it in your testing? or some other code is ignoring it?)

**Comment by TheAngryByrd** [comment] 2020-01-20 16:48
@baronfel just mentioned to me in Slack it's related to the different path separators and relative pathing. If I manually fix up the reference paths it seems to work.

```fsharp
let loadProject file =
    async {
        let! source = IO.File.ReadAllTextAsync file |> Async.AwaitTask
        let! (opts, error) = checker.GetProjectOptionsFromScript(file, SourceText.ofString source, assumeDotNetFramework = false, useSdkRefs = true, useFsiAuxLib = true, otherFlags = [|"--targetprofile:netstandard" |])
        let newOO =
            opts.OtherOptions
            |> Array.map(fun i ->
                if i.StartsWith("-r:") then
                    let path = i.Split("-r:", StringSplitOptions.RemoveEmptyEntries).[0]
                    sprintf "-r:%s" (IO.FileInfo(path).FullName)
                else
                    i
            )
        // dumpOpts opts
        return file,{ opts with OtherOptions = newOO}
    } |> Async.RunSynchronously
``` 

---

I think this issue now becomes whatever generates those `-r:` pats options should probably handle generating full path correctly.

**Comment by Krzysztof-Cieslak** [comment] 2020-01-20 16:50
@TheAngryByrd, was the issue happening in Ionide/FSAC or in Analyzers CLI? Anyway - we should move this issue to the appropriate repo.

**Comment by baronfel** [comment] 2020-01-20 16:55
He's testing analyzers using the FCS apis to typecheck, then passing that set of checkresults into the analyzer SDK. so this particular issue was about the AST coming from FCS not matching up, which was caused by the use of relative paths for the references, which comes from the DotnetFrameworkDependency code. This _might_ be fixed in the latest versions, which I haven't released as a new FCS image yet, but we should probably add a test to verify the invariant that the FCS apis return absolute paths for references.

**Closed** 2021-08-13 13:50 UTC
Labels: closed because repo moved to dotnet/fsharp
